sudo: false
language: python
python:
  - 3.6
  - 3.8

install: pip install tox-travis
script: tox

deploy:
  # deploy to PyPI on tags
  - provider: pypi
    server: https://upload.pypi.org/legacy/
    on:
      repo: typesupply/extractor
      tags: true
      all_branches: true
      python: 3.6
    user: anthrotype
    password:
      secure: j80CZr2m3srL2ZiIyXGQNx/od1zywo4O7nXg8PX4qKDmPX2CdMZW8b5ZkGZWRrLN2g/Ssd6Qo0WRQTkniz6/SDiBj4x9CJWJ+UbzIsJyAEEgiqF76Tp/kz0HESzJROwfuo67PX3bafyGWvBjDA9cS6xyp2j4rklq6+swCkbDk7NLmFqUps8XE1x4LIJFiF/hkDXxBvjXkitCHA9Z5NPViURujYLyWJ2mRBkWwyRN9q8xkH1pzo4OLuoblxi3u1kWhfcnJmZ3EX24g47oRqCPnChYKk4aArcoGPiRVclB7Ma6zE/fBtjqeMmaDmQw0g6HBFKLhJBXDc4hn8DNP6oGAtPi1FkKuG84CV/KwGGJ4/sulyuZj+73uZ8Hkr9hhEQBcqwWsyrYdzvQPUf1hdgScmGFnhdqubOY5+XOTGq5Jk1NvPg6K+yI9e6FxfWCWOD8Hzv4kz/qsbZ6JIEzb0c7EFnnRQFsTNbtB9ChJJol5dZCP7g5eQ+mZZVzxQ/l4VpZT7hdkb0UjBrk+eIJRgQGOIFM435Ul9bwp1ALddvnhytx++daFtk1/+6cd3kDbaeF+cHNkCsshfQE1O2E+GbEI+Ddm24Sw6dd2g6RbH4bBLdElFhMDx82SxgfNx7Jtx9NhNzqnOP9Xx+1NRRN1RXkxz9DFrs/KbNJOzv+qRk5ZP0=
    distributions: sdist bdist_wheel
    skip_upload_docs: true
  # also create a Github Release with current tag
  - provider: releases
    api_key:
      secure: Zfco0lC1K1ME79opimESfTq2gjoj702MDcSwm+r/+3mQbJaRROsUQTxtWMYrZ/VplQ8xQCFwO0f5BFZGcaEA/EbGb9DwjcUOpX54hIC1K4tFTWius8U8AuEwrVfvNNtGZRCpvyNVtkijVEM0CgrR8uFWYP4ZPpYOmYTNJH8DCHUw/kEfjjJJr7UKO7sv+7AxvotqDKANb+KuytiIzL1Z+cfD1h3uU7oOqB8fKNlZpE1GBaz+yPExLrGrlgsMWCKFUZShyHOIAM/JybzubX0+h3oyRAZKsn/5wN7Rs6cKnNR33Im+vECiIFlNW3g+GkiXbAAXZQKnJ2W41ShiIbwrk7jkD8ckkEj6JVJznj24h1ZwQ76EbL5YNAjAkFxeWFCfxHaL8z0h3wqoU/FLT6VPQoy1KFC3Vfne8l1n18rOVbWHHuS4xPvvjvl1k3itxh89pVUFR3wAgrcRAcyiNgpDHlS5+TsCz2h0cRSqRKP/PMwtztlQYdZChgUgH8mJIbLUQu5w1syWPGd4360q2OECmM3Xt/wFiCSH59DyZ2GPkSDEZMBzryRkLXliiKHZ2EUwI8kIwbrROCKRjPcUMQW64DX3HenrCBfNwHQ3756bg7ShtaylFvbls8sDFM/BNC406ok65OMW8db+xmQqJFqo0mU2hqRG3S0dP8k4Rst8l54=
    on:
      repo: typesupply/extractor
      tags: true
      all_branches: true
      python: 3.6
